#!/bin/bash
#
#    blockbackup - Block level inremental backup tool
#
#
#    Copyright (C) 2016-2019 Marek Wodzinski
#                  2024-     Andy Smith
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#


USE_ZIP=0
SOURCE=
DEST=
CHUNK=1M
DO_XXH=1
ZCAT="cat"
ZEXT=
STARTCHUNK=0
ENDCHUNK=
NOUPDATE=0
SKIPSAME=0
IGNORE_ERR=0

function usage() {
    echo "ERROR: unknown option/paramter"
    echo "Usage: blockbackup -s device -d directory [-z|-za] [-n num_zips] [-c chunk] [-mn] [-sc start] [-se end] [-nu] [-l] [-ss] [-ie]"
    echo "    -s|--source device     source device"
    echo "    -d|--dest directory    destination directory"
    echo "    -z|--zip               compress every block right after read/compare"
    echo "    -za|--zip-after        compress new blocks at the end of process"
    echo "    -c|--chunk N           set chunk size to N (default=1M)"
    echo "    -nx|--no-xxh           don't generate xxhash128 for every chunk"
    echo "    -sc|--start-chunk N    start dump from chunk N (default=0)"
    echo "    -ec|--end-chunk N      end dump at chunk N (default=end of device)"
    echo "    -nu|--no-update        don't update lastsync link at the end"
    echo "    -l|--symlink           use symbolic links instead of hard links"
    echo "    -ss|--skip-same        don't put link if reference chunk is the same"
    echo "    -ie|--ignore-errors    don't stop on dd errors, must be used with --end-chunk"
    exit 1
}


#get/parse parameters
while true; do
    case "$1" in
    -z|--zip)
        USE_ZIP=1
        ZCAT="zstdcat"
        ZEXT=.zst
        ;;
    -za|--zip-after)
        USE_ZIP=2
        ZCAT="zstdcat"
        ZEXT=.zst
        ;;
    -s|--source)
        shift
        SOURCE="$1"
        if [ ! -b "${SOURCE}" ]; then
        echo "ERROR: source must be device!"
        exit 1
        fi
        ;;
    -d|--dest)
        shift
        DEST="$1"
        if [ ! -d "${DEST}" ]; then
        echo "ERROR: destination must be existing directory"
        exit 1
        fi
        ;;
    -c|--chunk)
        shift
        CHUNK=$1
        ;;
    -nx|--no-xxh)
        DO_XXH=0
        ;;
    -sc|--start-chunk)
        shift
        STARTCHUNK=$(($1))
        ;;
    -ec|--end-chunk)
        shift
        ENDCHUNK=$(($1))
        ;;
    -nu|--no-update)
        NOUPDATE=1
        ;;
    -ss|--skip-same)
        SKIPSAME=1
        ;;
    -ie|--ignore-errors)
        IGNORE_ERR=1
        ;;
    *)
        usage
        ;;
    esac
    shift
    if [ -z "$1" ]; then break; fi
done

if [ -z "${SOURCE}" ] || [ -z "${DEST}" ]; then usage; fi
if [[ $IGNORE_ERR -eq 1 ]] && [[ -z "$ENDCHUNK" ]]; then usage; fi

if [[ $USE_ZIP -ne 0 ]]; then
    if [ -z "$ZSTD_CLEVEL" ]; then
        echo "Using default compression level 3; set ZSTD_CLEVEL to change"
    else
        echo "Using compression level $ZSTD_CLEVEL as requested"
    fi

    if [ -z "$ZSTD_NBTHREADS" ]; then
        echo "Using default single-threaded compression; set ZSTD_NBTHREADS to change"
    else
        if [[ $ZSTD_NBTHREADS -eq 0 ]]; then
            echo "Detecting number of compression threads as requested"
        else
            echo "Using $ZSTD_NBTHREADS compression thread(s) as requested"
        fi
    fi
fi

echo "Doing incremental backup of device ${SOURCE} to directory ${DEST} with chunk size ${CHUNK}"


TODAY=$(date +%F_%H%M%S)

cd "${DEST}" || exit 1
mkdir "${TODAY}"

# Base.
if [ -L lastsync ]; then
    BASE=$(readlink lastsync)
else
    BASE=""
fi


# Start copy.
while true; do
    NEWNAME=$(printf "%08d\n" $STARTCHUNK)
    echo -n "${NEWNAME} : "
    NEWDIR=${NEWNAME:0:5}
    mkdir -p "${TODAY}/${NEWDIR}"

    # Read a chunk.
    dd if="${SOURCE}" \
        of="${TODAY}/${NEWDIR}/${NEWNAME}" \
        count=1 \
        bs="${CHUNK}" \
        skip=${STARTCHUNK}  1>/dev/null 2>&1

    # shellcheck disable=SC2181
    if [ $? -ne 0 ] && [[ $IGNORE_ERR -eq 0 ]]; then
        # Error or eof
        echo "end of source or error"
        break
    else
        ${ZCAT} "${BASE}/${NEWDIR}/${NEWNAME}${ZEXT}" 2>/dev/null \
            | cmp "${TODAY}/${NEWDIR}/${NEWNAME}" 1>/dev/null 2>&1

        if [ $? -eq 0 ]; then
            # The same - remove and make hardlink to old one.
            rm "${TODAY}/${NEWDIR}/${NEWNAME}"

            if [[ $SKIPSAME -eq 0 ]]; then
                ln -v "${BASE}/${NEWDIR}/${NEWNAME}${ZEXT}" \
                    "${TODAY}/${NEWDIR}/${NEWNAME}${ZEXT}"

                if [ ${DO_XXH} -eq 1 ]; then
                    ln "${BASE}/${NEWDIR}/${NEWNAME}.xxh128" \
                        "${TODAY}/${NEWDIR}/${NEWNAME}.xxh128"
                fi
            fi
        else
            # Not the same - leave it.
            echo "new ${TODAY}/${NEWDIR}/${NEWNAME}"

            if [ ${DO_XXH} -eq 1 ]; then
                xxh128sum "${TODAY}/${NEWDIR}/${NEWNAME}" \
                    > "${TODAY}/${NEWDIR}/${NEWNAME}.xxh128"
            fi

            if [ ${USE_ZIP} -eq 1 ]; then
                # zstd this chunk immediately.
                zstd --rm --quiet "${TODAY}/${NEWDIR}/${NEWNAME}"
            fi
        fi

        STARTCHUNK=$(( STARTCHUNK+1 ))
        [ "${ENDCHUNK}" ] && [ ${STARTCHUNK} -gt ${ENDCHUNK} ] && break
    fi
done

if [ ${USE_ZIP} -eq 2 ]; then
    # zstd everything after.
    echo "zipping everything"
    find "${TODAY}" -type f -regex '.*[0-9][0-9][0-9][0-9]$' \
        | sort | while read -r tozip; do
        echo "	${tozip}"
        zstd --rm --quiet "${tozip}"
    done
fi

# Update lastsync link.
if [ ${NOUPDATE} -eq 0 ]; then
    rm lastsync 1>/dev/null 2>&1
    ln -s "${TODAY}" lastsync
fi
